version: '3.7'

services:
  ml:
    build:
      context: .
    command: sh -c "pip install -r requirements.txt && python3 manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8080 project.wsgi"
#    expose:
#      - 8080
    ports:
      - 80:8080
    environment:
      - DEBUG=False
      - SECRET_KEY=DJANGO_SECRET_KEY
